const FETCH_TRACKS = 'FETCH_TRACKS'
const FETCH_TOP_ARTISTS = 'FETCH_TOP_ARTISTS'
const UPDATE_SEEDS = 'UPDATE_SEEDS'
const FETCH_RECOMMENDED_TRACKS = 'FETCH_RECOMMENDED_TRACKS'
const FETCH_DISCOVER_WEEKLY_TRACKS = 'FETCH_DISCOVER_WEEKLY_TRACKS'
export { FETCH_TRACKS, FETCH_TOP_ARTISTS, UPDATE_SEEDS, FETCH_RECOMMENDED_TRACKS, FETCH_DISCOVER_WEEKLY_TRACKS}
